name: Deploy to Github Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ALGOLIA

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true # pull submodules theme/reimu

      - name: Cache Hugo resources
        uses: actions/cache@v4
        env:
          cache-name: cache-hugo-resources
        with:
          path: |
            resources
            submodules  # add cache for theme/reimu
          key: ${{ env.cache-name }}

      - uses: actions/setup-go@v5
        with:
          go-version: "^1.17.0"
      - run: go version

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true

      - name: Build
        run: hugo --minify --gc

      - name: Check if Algolia secrets are set
        run: |
          if [ -z "${{ secrets.ALGOLIA_APP_ID }}" ] || [ -z "${{ secrets.ALGOLIA_API_KEY }}" ]; then
            echo "Algolia App ID or API Key is not set properly!"
            exit 1
          else
            echo "Algolia secrets are set correctly."
          fi

      - name: Update Algolia Search Index
        uses: iChochy/Algolia-Upload-Records@main
        env:
          APPLICATION_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ADMIN_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          INDEX_NAME: biosite
          FILE_PATH: "public/algolia.json"
          
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
          clean: true
          single-commit: true
